spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: fitnessactivity

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5671}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    ssl:
      enabled: true

server:
  port: ${PORT:10000}

eureka:
  instance:
    prefer-ip-address: true
    

  client:
    service-url:
      defaultZone: https://fitness-microserivce.onrender.com/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking