spring:
  data:
    mongodb:
      uri: mongodb+srv://adminfit:admin123@cluster0.0cwkkt7.mongodb.net/?appName=Cluster0
      database: fitnessactivity

  rabbitmq:
    host: warthog.lmq.cloudamqp.com
    port: 5671
    username: bykfcrqi
    password: eZN83FJeO5bsD8BAcURvD59qBPNw_h64
    virtual-host: bykfcrqi
    ssl:
      enabled: true

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

  client:
    service-url:
      defaultZone: https://fitness-microserivce.onrender.com/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking