server:
  port: 8083

spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessreco
      database: fitnessreco

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

  client:
    service-url:
      defaultZone: https://fitness-microserivce.onrender.com/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange

  queue:
    name: activity.queue

  routing:
    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}