server:
  port: 8083

spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: fitnessreco

  rabbitmq:
    host: warthog.lmq.cloudamqp.com
    port: 5671
    username: bykfcrqi
    password: eZN83FJeO5bsD8BAcURvD59qBPNw_h64
    virtual-host: bykfcrqi
    ssl:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: https://fitness-microserivce.onrender.com/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange

  queue:
    name: activity.queue

  routing:
    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}