server:
  port: ${PORT:8081}

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${AIVEN_PG_HOST}:${AIVEN_PG_PORT}/fitness_user_db?sslmode=require
    username: ${AIVEN_PG_USER}
    password: ${AIVEN_PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://fitness-microserivce.onrender.com/eureka/