spring:
  application:
    name: eureka

server:
  port: ${PORT:8761}
  address: 0.0.0.0

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:https://fitness-microserivce.onrender.com/eureka/}

  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never