spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      enabled: false
      server:
        native:
          search-locations: classpath:/config

server:
  port: ${PORT:8888}

